name: Testing matrix based stratergies

on: 
   push

jobs:
    context-testing:
        runs-on: ubuntu-latest
        steps:
            - name: github contetx
              run: echo ${{github.string}}