name: Testing matrix based stratergies

on: 
   push

jobs:
    context-testing:
        runs-on: ubuntu-latest
        steps:
            - name: github contetx
              env:
                GITHUB_CONTEXT: ${{ toJson(github)}}
              run: echo "$GITHUB_CONTEXT"