name: Testing matrix based stratergies

on: 
   push

jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest, windows]
                images: [nginx, httpd]
        runs-on: ${{ matrix.os}}
        steps:
           - name: deploy the image
             run: docker run ${{matrix.images}}